### ISSUE TITLE
DLL injection not working

### ISSUE THREAD

**Issue by theLMGN** [iRandell/windows-process-manager#2]
If I try to inject to a process, nothing happens. I can use .NET code to inject the same DLL into the same process and it works. (nothing happens if I try to summon a .NET process to do it for me from Node, which maybe a culprit?)

**Comment by iRandell** [comment]
Check your target process and dll architecture. It's impossible inject x64 dll into x86 process. Also you can't inject x86 dll from x64 node.js process. Node.js process architecture should match dll architecture. You can set the architecture (ia32 or x64) of your dll in the .npmrc file to build this package properly as follows: arch=ia32
Set the architecture and reinstall this package.

**Comment by theLMGN** [comment]
Ah, I had a look yesterday, I didn't know the node (or in my case Electron) version mattered, II only thought only the DLL arch matttered.
